CREATE TABLE IF NOT EXISTS t_config (
	i_div character varying(30),
	i_type character varying(30)
);

CREATE TABLE IF NOT EXISTS t_frh_calc (
	i_div character varying(30),
	d_timestamp timestamp,
	i_tube_no numeric,
	n_mw real,
	n_att1 real,
	n_att2 real,
	n_att3 real,
	n_att4 real,
	n_att5 real,
	n_att6 real,
	n_att7 real,
	n_att8 real,
	n_att9 real,
	n_att10 real,
	n_att11 real,
	n_att12 real,
	n_att13 real,
	n_att14 real,
	n_att15 real,
	n_att16 real,
	n_att17 real,
	n_att18 real,
	n_att19 real,
	n_att20 real,
	n_att21 real,
	n_att22 real,
	n_att23 real
);

CREATE TABLE IF NOT EXISTS t_fsh_calc (
	i_div character varying(30),
	d_timestamp timestamp,
	i_tube_no numeric,
	n_mw real,
	n_att1 real,
	n_att2 real,
	n_att3 real,
	n_att4 real,
	n_att5 real,
	n_att6 real,
	n_att7 real,
	n_att8 real,
	n_att9 real,
	n_att10 real,
	n_att11 real,
	n_att12 real,
	n_att13 real,
	n_att14 real,
	n_att15 real,
	n_att16 real,
	n_att17 real,
	n_att18 real,
	n_att19 real,
	n_att20 real,
	n_att21 real,
	n_att22 real,
	n_att23 real,
	n_att24 real,
	n_att25 real,
	n_att26 real,
	n_att27 real,
	n_att28 real,
	n_att29 real,
	n_att30 real,
	n_att31 real,
	n_att32 real,
	n_att33 real,
	n_att34 real,
	n_att35 real,
	n_att36 real,
	n_att37 real,
	n_att38 real,
	n_att39 real,
	n_att40 real,
	n_att41 real,
	n_att42 real,
	n_att43 real,
	n_att44 real,
	n_att45 real,
	n_att46 real,
	n_att47 real
);

CREATE TABLE IF NOT EXISTS t_gas_temp (
	d_timestamp timestamp,
	n_mw real,
	n_frh_inlet real,
	n_fsh_inlet real,
	n_ltrh_inlet real,
	n_eco2_inlet real
);
